# Pytorch

### Tensor Functions

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab. It is free and open-source software released under the Modified BSD license.

The below mentioned functions used to manipulate tensors by performing various operations on it.

- rand
- from_numpy
- backward
- addmm
- eq

In [1]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.rand

rand function is used to generate tensors of random numbers which are uniformly distributed on the interval [0,1). 

In [2]:
# Example 1 - working 
a = torch.rand(4,requires_grad=True)
a

tensor([0.3990, 0.1746, 0.9818, 0.8790], requires_grad=True)

Here we send 4 as the parameter 'size' so, it returns tensor with 4 random numbers.
If autograd should record operations on the returned tensor or for computing 
derivatives we have to set "requires_grad" to True.

In [3]:
# Example 2 - working
torch.rand(2,4)

tensor([[0.4990, 0.2728, 0.2390, 0.6764],
        [0.9587, 0.0845, 0.7853, 0.8012]])

We send two parameters "2" and "4" as size to rand function which then returns a tensor of 2 dimensional array with 2 rows and 4 columns.

In [4]:
# Example 3 - breaking
torch.rand(2,4,dtype=torch.int64)

RuntimeError: _th_uniform_ not supported on CPUType for Long

For rand function datatype cannot be torch.int32 or torch.int64 as uniform distribution only supports torch.float32 or torch.float64 datatype.

We use rand function for generating tensors with random values that are uniformly distributed and similarly we can also use randn function for tensors with normally ditributed values.

## torch.from_numpy

This function creates a tensor from "numpy.ndarray". Modifications to the tensor will be reflected in the ndarray and vice versa as the returned tensor and numpy.ndarray share the same memory. But the returned tensor is not resizable.

In [7]:
# Example 1 - working
a = np.array([1,2,3,4])
t1 = torch.from_numpy(a)
t1

tensor([1, 2, 3, 4], dtype=torch.int32)

We created a 1D numpy array at first and by using "from_numpy" function we created a tensor.

In [8]:
# Example 2 - working
b = np.array([[1.,2],
              [3,4]])
t2 = torch.from_numpy(b)
t2

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

We created a tensor from 2-Dimensional numpy array by passing it as a parameter to "from_numpy" function.

In [9]:
# Example 3 - breaking
c = np.array(['s','w','a','r'])
t = torch.from_numpy(c)

TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.

"from_numpy" function cannot create tensors from numpy.ndarray which has values of 'str' type.

This function helps us in managing interoperability between numpy and tensors. We can create tensors from numpy arrays using this function. 

## torch.backward

This function computes the gradient of current tensor with respect to graph leaves.
You might need to zero the leaves sometimes before calling the function as it accumulates gradients in the leaves.

In [7]:
# Example 1 - working
a = torch.tensor([1],requires_grad=True,dtype=torch.float64)
b = torch.tensor([2],requires_grad=True,dtype=torch.float64)
x = torch.tensor([3.])
Y = x+a*b
Y.backward()
print(a.grad,b.grad,x.grad)

tensor([2.], dtype=torch.float64) tensor([1.], dtype=torch.float64) None


We created a tensor 'Y' from tensors a,b,c and x. When we perform the "backward" function on 'Y' which computes gradients w.r.t the leaves which are a,b,c and they will be storing in their respective '.grad' properties. x.grad is None as it is a leaf.

In [8]:
# Example 2 - working
x = torch.rand(2)
a = torch.tensor([1,2],requires_grad=True,dtype=torch.float64)
b = torch.tensor([1,3],requires_grad=True,dtype=torch.float64)
c = torch.tensor([1,4],requires_grad=True,dtype=torch.float64)
y = a*x*x+b*x+c
y.backward(x,create_graph=True,retain_graph=True)
print(a.grad,b.grad,sep='   ')

tensor([0.4328, 0.1684], dtype=torch.float64)   tensor([0.5721, 0.3049], dtype=torch.float64)


When we set create_graph to True then the graph of the derivative will be constructed, allowing to compute higher order derivative products. When we are training a model, the graph will be re-generated for each iteration. Therefore each iteration will consume the graph if the retain_graph is false, in order to keep the graph, we need to set it be true.

In [9]:
# Example 3 - breaking
x = torch.rand(2)
y = x+a*b
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [21]:
x = torch.rand(2)
y = x+a*b
a.grad.data.zero_()
y.backward(x)
a.grad, b.grad

(tensor([0.0374, 2.1370], dtype=torch.float64),
 tensor([ 6.6686, 12.7204], dtype=torch.float64))

This error generated as the tensor is non-scalar i.e. its data has more than one element. So, The function additionally requires specifying gradient. It should be a tensor of matching type and location, that contains the gradient of the differentiated function w.r.t. self. In the above example, 'x' is a scalar type and 'a','b' are non-scalar types.

backward function is used to compute derivatives or gradients of tensors with respect to graph leaves.

## torch.addmm

This function performs matrix multiplication of two matrices(i.e.mat1 and mat2) and add that matrix to input matrix(i.e.input).

out= βinput + α(mat1 @ mat2)

alpha and beta are scaling factors on matrix-vector product between mat1 and mat2 and the added matrix input respectively.

In [12]:
# Example 1 - working

a = torch.randn(3,2)
mat1 = torch.randn(3,4)
mat2 = torch.randn(4,2)
mat = torch.addmm(a,mat1,mat2)
mat

tensor([[ 2.4900,  0.8794],
        [ 0.2282, -0.5765],
        [ 0.9990, -2.3849]])

We had generated matrices using "randn" function and added the multiplied matrix(i.e.mat1 @ mat2) to input matrix by using "addmm" function.

In [13]:
# Example 2 - working

torch.addmm(a,mat1,mat2,beta=2,alpha=2,out=mat)
mat

tensor([[ 4.9801,  1.7588],
        [ 0.4564, -1.1530],
        [ 1.9980, -4.7698]])

We passed beta and alpha values also here and 'out = mat' represents the result stored in variable a.
We can assign only already declared variables to the 'out' parameter. It performs this operation: out= βinput + α(mat1 @ mat2)  where α=β=2.

In [14]:
# Example 3 - breaking
mat = torch.rand(4,3)
torch.addmm(a,mat1,mat,beta=2,alpha=2)

RuntimeError: The expanded size of the tensor (3) must match the existing size (2) at non-singleton dimension 1.  Target sizes: [3, 3].  Tensor sizes: [3, 2]

Here the error raises as the Input matrix (size:[3,2]) cannot be added to matrix mutiplication result ([size:[3,3]) as both sizes are different.

We can perform matrix multiplication and addition by using this function.

## torch.eq

It computes the element-wise equality of tensors.

In [15]:
# Example 1 - working
a = torch.tensor([10,20])
b = torch.tensor([10,10])
torch.eq(a,b,out=a)
a

tensor([1, 0])

We created 2 tensors a and b. Now, we compared element-wise between 2 tensors and the result stored in the variable 'a'.
Function returns '1' if values are same and '0' if values are different to the output variable 'a'.

In [16]:
# Example 2 - working
t = torch.tensor([1])
torch.eq(a,t)

tensor([ True, False])

We can compare tensor with single element and tensor with multiple elements like above.

In [17]:
# Example 3 - breaking
t = torch.tensor([4,7,8,8])
torch.eq(t,a)

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0

In [4]:
a = torch.tensor([10,20])
b = torch.tensor([10,10])
t = torch.tensor([1])
torch.eq(a,other = b,* = t)

SyntaxError: invalid syntax (<ipython-input-4-2f8f6573a44b>, line 4)

We cannot compare element-wise between the two tensors which are of different sizes except the case mentioned in the example-2.

By using this function We can compare elements of any two tensors.

## Conclusion

In this notebook, We discussed how to create tensors with random elements, creating tensors from numpy.ndarray and to interoperate between tensors and numpy, To compute gradients using 'backward' function, To compare two tensors element-wise using 'eq' function, To perform addition and multiplication operations on tensors.

You can refer below links for further information.

## Reference Links

[torch.rand](https://pytorch.org/docs/master/generated/torch.rand.html?highlight=rand#torch.rand)

[torch.from_numpy](https://pytorch.org/docs/master/generated/torch.from_numpy.html?highlight=from_numpy#torch.from_numpy)

[torch.backward](https://linlinzhao.com/tech/2017/10/24/understanding-backward()-in-PyTorch.html)

[torch.addmm](https://pytorch.org/docs/master/generated/torch.addmm.html?highlight=addmm#torch.addmm)

[torch.eq](https://pytorch.org/docs/master/generated/torch.eq.html?highlight=eq#torch.eq)



In [18]:
!pip install jovian --upgrade --quiet

In [19]:
import jovian

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/sswaroop46/01-tensor-operations


'https://jovian.ml/sswaroop46/01-tensor-operations'

### Some other Functions

## torch.sort

This function sorts the elements of the input tensor along a given dimension in ascending or descending order by value.

In [22]:
# Example 1 - working
b = np.array([[6.2,2],
              [4,5]])
t2 = torch.from_numpy(b)
torch.sort(t2)

torch.return_types.sort(
values=tensor([[2.0000, 6.2000],
        [4.0000, 5.0000]], dtype=torch.float64),
indices=tensor([[1, 0],
        [0, 1]]))

In [25]:
# Example 2 - working
torch.sort(t2,dim=0)

torch.return_types.sort(
values=tensor([[4.0000, 2.0000],
        [6.2000, 5.0000]], dtype=torch.float64),
indices=tensor([[1, 0],
        [0, 1]]))

In [22]:
# Example 3 - working
sorted,indices = torch.sort(t2)
print(sorted)
indices

tensor([[2.0000, 6.2000],
        [4.0000, 5.0000]], dtype=torch.float64)


tensor([[1, 0],
        [0, 1]])

For more Information : https://pytorch.org/docs/master/generated/torch.sort.html?highlight=sort#torch.sort

## chunk

This function splits a tensor into a specific number of chunks. Each chunk is a view of the input tensor.
Last chunk will be smaller if the tensor size along the given dimension dim is not divisible by chunks.

In [23]:
# Example 1 - working
torch.chunk(t1,2)

(tensor([1, 2], dtype=torch.int32), tensor([3, 4], dtype=torch.int32))

In [24]:
# Example 2 - working
torch.chunk(t2,2,dim=0)

(tensor([[6.2000, 2.0000]], dtype=torch.float64),
 tensor([[4., 5.]], dtype=torch.float64))

In [25]:
# Example 3 - working
t = torch.tensor([[4,8],
                  [1,2]],dtype=torch.int32)
torch.chunk(t,2,1)

(tensor([[4],
         [1]], dtype=torch.int32), tensor([[8],
         [2]], dtype=torch.int32))

In [26]:
# Example 4 - working
x = torch.arange(0, 11)
x.chunk(8)

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([6, 7]),
 tensor([8, 9]),
 tensor([10]))

For more information : https://pytorch.org/docs/master/generated/torch.chunk.html?highlight=chunk#torch.chunk

## clamp

This function clamp all elements in input into the range [ min, max ] and return a resulting tensor.

In [27]:
# Example 1 - working
a = torch.randn(6)
torch.clamp(a,min=-0.2,max=.8)

tensor([ 0.8000,  0.8000, -0.2000, -0.2000,  0.7809,  0.8000])

In [28]:
# Example 2 - working
a = torch.randn(6,4)
torch.clamp(a,max=2.,out=a)

tensor([[ 1.4692,  0.5391,  0.1045,  0.6506],
        [ 0.4412, -0.7133, -0.2337, -1.5112],
        [-1.0779,  1.0014, -2.5630,  0.4715],
        [ 0.8659, -0.1016,  0.9444, -1.3301],
        [ 0.9607,  0.3419, -0.1765, -1.5689],
        [ 0.7167, -0.7932,  0.8514, -0.0515]])

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.randn(2,3,4)
torch.clamp_(a,min = -2,max = 0)

tensor([[[ 0.0000, -0.2144, -0.4886,  0.0000],
         [ 0.0000, -1.0345, -1.4178,  0.0000],
         [-0.1557, -1.0319, -1.1309,  0.0000]],

        [[-0.1623, -0.6033, -0.6689,  0.0000],
         [ 0.0000, -0.6037, -0.0890,  0.0000],
         [-0.2162,  0.0000,  0.0000, -0.4691]]])

For more information : https://pytorch.org/docs/master/generated/torch.clamp.html?highlight=clamp#torch.clamp